// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Anime: typeof import('./components/Anime.vue')['default']
    App: typeof import('./App.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
  }
}

export { }
